source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

target 'mytool-oc' do
pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage',   '~>3.8'
pod 'MBProgressHUD', '~> 1.0.0'
pod 'SDCycleScrollView','~> 1.64'
pod 'Masonry'
pod 'SDAutoLayout', '~> 2.1.3'
pod 'SVProgressHUD', '~>2.1.2'
pod 'Masonry'

#pod 'TTTAttributedLabel', '1.10.1'
#pod 'RegexKitLite-NoWarning', '1.1.0'
#pod 'hpple', '0.2.0'

#pod 'TPKeyboardAvoiding', '1.2.4'
#pod 'BlocksKit', '2.2.5'
#pod 'ReactiveCocoa', '2.3.1'
#pod 'MMMarkdown', '0.3'


#pod 'NYXImagesKit', '2.3'
#pod 'UIImage+BlurredFrame', '0.0.4'
#pod 'POP+MCAnimate', '2.0.1'
#pod 'PPiAwesomeButton', '1.5.2'
#pod 'APParallaxHeader', '0.1.6'
#pod 'SDCAlertView', '2.5.2'
#pod 'MarqueeLabel', '2.5.0'
#pod 'TMCache', '2.1.0'
#pod 'iVersion', '1.11.4'
#pod 'JazzHands', '2.0.0'
#pod 'SSKeychain', '1.2.3'

#pod 'evernote-cloud-sdk-ios', '2.0.2'

#pod 'FLEX', '~> 2.0', :configurations => ['Debug']
end
